# -*- coding: utf-8 -*-
"""PDF Question Answering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YlYFM8M3viqE_HpbVOA8XcM6-3x5a3uv
"""

! pip install transformers gradio pymupdf

import gradio as gr
import fitz
from transformers import pipeline

pipeline = pipeline("text2text-generation", model="google/flan-t5-large")

def read_pdf(pdf_file):
    doc = fitz.open(pdf_file.name)
    text = ""
    for page in doc:
        text += page.get_text("text")
    return text

def answer_question(pdf_file, question):
    if not pdf_file:
        return "Please upload a PDF file."
    if not question.strip():
        return "Please enter a question."

    context = read_pdf(pdf_file)
    if not context.strip():
        return "The PDF has no readable text."

    prompt = f"Context: {context}\n\nQuestion: {question}\nAnswer:"

    result = pipeline(prompt, max_length=200, do_sample=True)

    return result[0]['generated_text']

demo = gr.Interface(
    fn=answer_question,
    inputs=[
        gr.File(type="filepath", label="Upload PDF"),
        gr.Textbox(lines=2, placeholder="Enter your question here...", label="Question")
    ],
    outputs=gr.Textbox(label="Answer"),
    title="PDF Question Answering",
    description="Upload a PDF and ask any question. The model will generate a full answer from the document."
)

if __name__ == "__main__":
    demo.launch()